### ISSUE TITLE
UDP Discovery Packet

### ISSUE THREAD

**Issue by adurosmart** [actions-on-google/smart-home-local#11]
1、In the documentation, I see that I want to fill in a fixed discovery packet. However, the data received by my gateway is encrypted. Each gateway needs to receive a different discovery device packet.What should I do in this situation?
2、IntentFlow.IdentifyResponse Can return multiple device data at a time, what should I do?
Thanks.

**Comment by veonua** [comment]
1. that sounds crazy, how do you know the key for every gateway? maybe gateway should be changed to be more discoverable, like mDNS or uPNP

2. see hub implementation (in dev currently in progress)

**Comment by devunwired** [comment]
Hi @adurosmart, thanks for your feedback.

1. Can you describe in more detail how you typically handle this situation? How does your application determine which encryption key is needed for each gateway? It would seem you would need to identify the device somehow first to know which encryption key to use (e.g. serial number or some other identifier)?
2. You can find additional details on the discovery process [in the documentation](https://developers.google.com/actions/smarthome/develop/local#support_devices_behind_a_hub). Specifically, the `IDENTIFY` intent would be used to discover your gateway device, and the `REACHABLE_DEVICES` intent would enable you to report the end devices that gateway is capable of controlling.

**Comment by adurosmart** [comment]
Thank you reply.
Our gateway periodically broadcasts an unencrypted identification code. After the APP receives the identification code from the broadcast, the APP reads an external encryption key, after which the encrypted data between the APP and the gateway can be decrypted.

**Comment by devunwired** [comment]
Thanks @adurosmart, can you file a feature request in our [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327) for this use case?

The local home platform doesn't currently support a "listen only" mode where you could define a packet (or packet format) the Home device expects to **receive** from your gateway. The **UDP Discovery Packet** is the packet _broadcast by the Home device_ that your device is expected to respond to. So in the current implementation, your device would need to listen for a fixed broadcast from the Home device and then reply with the identification code (which would be delivered to your app's `IDENTIFY` handler).
