### ISSUE TITLE
UDP discovery doesn't start

### ISSUE THREAD

**Issue by smairesse** [actions-on-google/smart-home-local#14]
I setup up the sample as a single end device but it seems that the Google Home doesn't start the udp discovery.

When I connect to http://local-dev-server-hostname-or-ip:8080/, the only log is :
```
Uncaught ReferenceError: cast is not defined
    at new pc (smarthome_sdk.js:54)
    at new V (smarthome_sdk.js:197)
    at Pg (smarthome_sdk.js:200)
    at W.l.getDeviceManager (smarthome_sdk.js:200)
    at W.l.onExecute (smarthome_sdk.js:201)
    at Module../index.ts (index.ts:22)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```
It appears at this line : if (cast.__platform__ && cast.__platform__.channel) in the Local Home SDK : //www.gstatic.com/eureka/smarthome/smarthome_sdk.js Maybe you know what's wrong ?

**Comment by Fleker** [comment]
The code will run on Google Home devices but won't run on a local browser. If you check [the guide](https://developers.google.com/assistant/smarthome/develop/local) you can see how to use Chrome devtools to do debugging from a Google Home.

**Comment by smairesse** [comment]
Thanks Fleker for your response.

Into DevTools window, i have 

```
Ready, App version: 0.0.1
bundle.js:268 Ready
smarthome_sdk.js:122  [  0.027s] [smarthome.DeviceManager] Cast shell version: 1.44 
smarthome_sdk.js:122  [  0.028s] [smarthome.DeviceManager] SDK version: 3.0.1 

```
But i don't see IDENTIFY intent response in this console.

In the window where run the virtual light strip, i can see :

```
discovery listening { address: '0.0.0.0', family: 'IPv4', port: 3311 }
opc listening { address: '::', family: 'IPv6', port: 7890 }
received discovery payload: <Buffer a5 a5 a5 a5> from: { address: '_GoogleHomeLocalAddress_', family: 'IPv4', port: 3312, size: 4 }
sent discovery response: { id: 'strand1',
  model: 'fakecandy',
  hw_rev: 'evt-1',
  fw_rev: 'v1-beta',
  channels: [ 1 ] } to: { address: '_GoogleHomeLocalAddress_', family: 'IPv4', port: 3312, size: 4 }
```

I don't understand why discovery doesn't work ?

**Comment by smairesse** [comment]
Thanks Fleker for your response. It's run now.
