### ISSUE TITLE
udpScanData access in REACHABLE_DEVICES ?

### ISSUE THREAD

**Issue by gytisgreitai** [actions-on-google/smart-home-local#15]
Any way to access udpScanData in `REACHABLE_DEVICES` ? I need to get the port that was provided by udpScanData. I can access it in `IDENTIFY` but not in `REACHABLE_DEVICES`. It does not seem to be possible to return custom data with `IDENTIFY` response ? REACHABLE_DEVICES seems to have customData property but the code comments say it is not present for hub devices. I could just put it as a global variable, but is this the way to go?

**Comment by devunwired** [comment]
Thanks for reporting this.
Can you file this issue on the [developer preview issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327)? It looks like there's a mismatch in fields between what the preview SDK is currently returning to intents and what we have documented in the typings.

**Comment by PizlaTheDeveloper** [comment]
I agree. I also needed to transfer parameters from `IDENTIFY `intent to `REACHABLE_DEVICES` like a port. I made port as a part of proxy's device ID.

**Comment by devunwired** [comment]
Migrating this issue to the [preview issue tracker](https://issuetracker.google.com/issues/148137512).
