### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by raintonr** [actions-on-google/smart-home-local#16]
Forgive me, but isn't this whole project a duplicate of...

https://github.com/googlecodelabs/smarthome-local

... not that I can get either of these to work :(

**Comment by devunwired** [comment]
This repository contains the Getting Started sample code.
The repository you linked contains the companion project for the [local execution codelab](https://codelabs.developers.google.com/codelabs/smarthome-local).

If you believe you've found an issue with the code in this repository, feel free to file an issue. For general development questions with Google Smart Home or Local Home SDK, please post on our community forums:
Reddit: https://www.reddit.com/r/GoogleAssistantDev/
StackOverflow: https://stackoverflow.com/questions/tagged/google-smart-home

**Comment by raintonr** [comment]
Thanks, but that's my point - the local execution codelab has a detailed explanation and seems more complete so why does this (https://github.com/actions-on-google/smart-home-local) exist?

FWIW, I tried https://github.com/actions-on-google/smart-home-local but failed to get very far.

I was also having issues with https://github.com/googlecodelabs/smarthome-local specifically issues linking the test action to my Home Graph but have progressed more with that project now. I think that was actually caused a bug in the smartphone app and will discuss more in that other repo.

**Comment by devunwired** [comment]
> Thanks, but that's my point - the local execution codelab has a detailed explanation and seems more complete so why does this (https://github.com/actions-on-google/smart-home-local) exist?

Codelabs are meant to walk through a specific implementation step by step in detail. Samples are fully worked implementations that typically focus on showcasing the full API surface.

In this case, the codelab showcases a single end device (washer) using local execution and the sample showcases both single and hub-based integrations with RGB lights.

Hope that helps.
