### ISSUE TITLE
https with self-signed certificates

### ISSUE THREAD

**Issue by PizlaTheDeveloper** [actions-on-google/smart-home-local#17]
Hi, is it possible to make https requests using DeviceManager on server with self-signed certificate? I get `COMMAND_FAILED` error code with `"Did not receive HTTP response."`. I don't know if it is related to the self-signed certificate problem?

**Comment by devunwired** [comment]
As of now, this is not currently supported. Please feel free to file a Feature Request on the [preview issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327) with additional details about your use case.
