### ISSUE TITLE
IDENTIFY requests for googlerpc._googlerpc._tcp.local

### ISSUE THREAD

**Issue by PizlaTheDeveloper** [actions-on-google/smart-home-local#19]
Hi,
I use MDNS discovery service for discovering my devices for local API. I use MDNS service name as a filter but after rebooting I have requests for Identification of device with `googlerpc._googlerpc._tcp.local ` and sometimes other google's services
Is it ok? Why my filter is not respected here? 
It is not big problem for me to check correct service name in the processing of the IDENTIFY request and reject it.

`mdnsScanData: {serviceName: "googlerpc._googlerpc._tcp.local", name: "googlerpc", type: "googlerpc", protocol: "tcp", data: Array(1), …}`
...
`smarthome_sdk.js:122  [  0.074s] [smarthome.DeviceManager] Got a rejected promise Invalid service name`

**Comment by devunwired** [comment]
A couple things to note here. First, I would recommend you enroll your device in the Cast Preview Program as described in the [developer guide](https://developers.google.com/assistant/smarthome/develop/local#before_you_begin). This will allow you to get the latest firmware for testing. There were some updates in the latest preview platform that change this behavior slightly.

> I use MDNS service name as a filter but after rebooting I have requests for Identification of device

There are actually two parts to this, and you'll want to make sure you implement both. The [mDNS Scan Configuration](https://developers.google.com/assistant/smarthome/develop/local#set_up_the_scan_config_information) should have both the **Service Name** and **Name** attributes set. The former sets up the service the device will scan for, and the latter acts as the filter to determine which responses reach your app.

**Comment by PizlaTheDeveloper** [comment]
> A couple things to note here. First, I would recommend you enroll your device in the Cast Preview Program as described in the developer guide. This will allow you to get the latest firmware for testing. There were some updates in the latest preview platform that change this behavior slightly.

Ok

> There are actually two parts to this, and you'll want to make sure you implement both. The mDNS Scan Configuration should have both the Service Name and Name attributes set. The former sets up the service the device will scan for, and the latter acts as the filter to determine which responses reach your app.

I think that one of the option was documented as optional, but no problem, I changed that and probably works well now.

Thank you for clarification
