### ISSUE TITLE
Add sample for hub device

### ISSUE THREAD

**Issue by proppy** [actions-on-google/smart-home-local#2]
The sample should show:
- what to return in `IDENTIFY` for the hub device
- how to retrieve and return `vericationIds` in `REACHABLE_DEVICES`
- how to handle `PROXY_SELECTED`
- how to forward `opc` message in `EXECUTE` to the hub w/ additional metadata so that the hub can reach the appropriate target devices
- how the local home app can discover the hub, and how the hub can discover child devices

**Comment by peterjuras** [comment]
This would be very helpful. I can't get it to work using a proxy device and the types appear to be missing some information.

**Comment by madgeni** [comment]
Can we please get this? I have literally no idea where to start getting this working.

**Comment by proppy** [comment]
@madgeni Note this is currently blocked by https://github.com/actions-on-google/smart-home-local/issues/1#issuecomment-515920552, i.e: publishing documentation and bindings for the `PROXY_SELECTED` intent.

**Comment by madgeni** [comment]
Thanks @proppy - i'm struggling to understand the flow, and the general approach. 
I've updated the Sync, and an initial handler (i'm using pure JS, so it's based on my existing cloud handlers), just so i can start testing. But nothing appears under chrome://inspect/#devices

**Comment by proppy** [comment]
@madgeni did you manage to complete the flow for a non-hub device?
@madgeni in addition to handling of `PROXY_SELECTED` there are multiple things that the sample should implement in order to demonstrate the SDK usage for hub devices, I updated the original issue description to reflect that: https://github.com/actions-on-google/smart-home-local/issues/2#issue-467212765

**Comment by madgeni** [comment]
no, my solution uses a hub, which in turn handles the devices via a set of APIs.
I can't equate this to the cloud service, where the app specifies a URL (https://myserver.com/ha), which then handles the intents. I can stare at the example for hours not understanding- 
import App = smarthome.App;
const localHomeApp: App = new App("1.0.0");
localHomeApp
  .onExecute(executeHandler)
  .onIdentify(identifyHandler)
  .listen()
  .then(() => {
    console.log("Ready");
  });

Am i thinking too much about it? Is this just a node server, which handles the intents? Can i deploy it using express (like my cloud service)?

**Comment by proppy** [comment]
@madgeni the intent handling happens in [app/app.ts](https://github.com/actions-on-google/smart-home-local/blob/3f4e7ca84868e172acc5e81c096e35778adeec5c/app/app.ts), the local app is automatically deployed to your Home devices using the [test URL](see https://developers.google.com/actions/smarthome/develop/local#test_device_control)) specified in the actions on google console during development and using the bundled version that you uploaded during production.

What's missing for you to properly implement hub support is what listed in https://github.com/actions-on-google/smart-home-local/issues/2#issue-467212765, but I would recommend to try out the sample with a single device like this [one](https://github.com/actions-on-google/smart-home-local/tree/master/device) in order to get more familiar with the SDK.

**Comment by madgeni** [comment]
Thanks - i think i'll wait until there's some clearer documentation on the hub implementation.

**Comment by chearmstrong** [comment]
@madgeni I'm using vanilla JS too. The key thing is that you're bundling with [Webpack](https://github.com/actions-on-google/smart-home-local/blob/master/app/webpack.config.js) (my Webpack config is below) and which injects your bundle to the HTML page (where the SDK is available). `smarthome` is available in the global scope (I don't think that's clear from the docs/examples). I have this in my `index.js`.

### Index (`src/index.js`)

```JavaScript
/**
 * Global dependencies.
 */
const smarthomeApp = new smarthome.App('0.0.1') // `smarthome` is defined globally in the app

/**
 * Internal dependencies.
 */
const execute = require('./handers/execute-handler')
const indentify = require('./handers/identify-handler')
const reachableDevices = require('./handers/reachable-devices-handler')

smarthomeApp
    .onExecute(execute)
    .onIdentify(indentify)
    .onReachableDevices(reachableDevices)
    .listen()
    .then(() => console.log('ready...'))
```

### Webpack for Vanilla JS (in project root)

```
/**
 * External dependencies.
 */
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  devtool: 'inline-source-map',
  devServer: {
    contentBase: './dist',
    inline: false
  },
  resolve: {
    extensions: ['.js']
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.html',
      inject: 'head'
    })
  ]
}
```

### HTML file
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Local Home SDK App</title>
    <script src="//www.gstatic.com/eureka/smarthome/smarthome_sdk.js"></script>
  </head>
  <body>
  </body>
</html>
```

**Comment by madgeni** [comment]
Thanks @chearmstrong - appreciate it :)

**Comment by madgeni** [comment]
Doesn't look like the identify handler is being hit - honestly, this is exhausting. I get no errors in the console.

**Comment by devunwired** [comment]
Hey folks, for updates on the situation here I would recommend tracking Issue #1

**Comment by devunwired** [comment]
We've updated this sample to include a hub use case, and included some additional detail in the [implementation guide](https://developers.google.com/assistant/smarthome/develop/local) for hubs.

Please note one item in the updated documentation, you have to opt your test devices into the **Cast Preview Program** to test this functionality with the latest Cast firmware, which has not rolled out yet to production devices.
