### ISSUE TITLE
Jest issues : smarthome is not defined

### ISSUE THREAD

**Issue by rajaona-jean** [actions-on-google/smart-home-local#20]
Hi,
I use Jest to test my code but when i run a test, the error: "ReferrenceError: smarthome is not defined"  occurs when I try to import the tested function. Did you face this isssue with ava ?

**Comment by proppy** [comment]
You should be able to take inspiration from the Local Home application test at:
https://github.com/actions-on-google/smart-home-local/blob/master/app/test.ts

I would suggest you raise this as question on https://stackoverflow.com/questions/tagged/google-smart-home question, as this project only track issues related to the Local Home SDK sample.
