### ISSUE TITLE
smarthome_sdk.js:63 Uncaught ReferenceError: cast is not defined

### ISSUE THREAD

**Issue by youngda** [actions-on-google/smart-home-local#21]
![git](https://user-images.githubusercontent.com/12874231/76431167-33c1ec00-63ec-11ea-9f5c-86da996de314.png)
Following the tutorial, I don't know what went wrong.

**Comment by devunwired** [comment]
[Testing](https://github.com/actions-on-google/smart-home-local#test-the-local-execution-app) must be done on a supported Home/Nest device, as the Local Home SDK binary is not available in the browser (it is only present on those devices).

**Comment by youngda** [comment]
> [测试](https://github.com/actions-on-google/smart-home-local#test-the-local-execution-app)必须在受支持的Home / Nest设备上进行，因为本地Home SDK二进制文件在浏览器中不可用（仅在那些设备上存在）。

thank you for your help
