### ISSUE TITLE
Where can I find my Client ID and Client secret.

### ISSUE THREAD

**Issue by Milan991** [actions-on-google/smart-home-local#23]
I've deployed firebase functions. 
Where can I find **Client ID** and **Client secret** 

Instructions are saying next: 

> **Client ID::** placeholder-client-id
> **Client secret::** placeholder-client-secret

**Comment by Fleker** [comment]
The client ID and secret are provided by you as the developer for your OAuth implementation. As this is a sample, you should be fine with using the placeholders.

**Comment by Milan991** [comment]
@Fleker Thanks, so I will just copy-paste the "placeholder-client-id".
One more question, does the instruction below means that I should go to the Google Home App and just simply add the device from the list?

> Trigger a SYNC request by linking the placeholder smarthome provider to your account in the Google Home app.

**Comment by Fleker** [comment]
Yes that step means you add the device through the Google Home app.

**Comment by Milan991** [comment]
@Fleker Thanks, closing the issue now.

**Comment by Milan991** [comment]
@Fleker Can you help me with this error

> Error: Forbidden
> Your client does not have permission to get URL /authorize?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fhome-300bd&client_id=placeholder-client-id&response_type=code&state=AFVGnUGxgfsqVpMyJUXH404ET8xvoxkUQlJ9sc0EKKNkakwJAS1p2541fE3NAo_cSBJlmpF8TjRViAn-nRcfOuNzEmVjXYhU46Aatk8ZULRkwBdlGQ-O3GU2YX7qH-P_5vDyqgp7TzZvZIlmzbylTK7H5RStNj_wRfWDvK2qQpGpu7E-q7aB-OnSokwl05yilibH1o0kK0r6_rlFYtD__JFFlowV8uFLH9yziHXuGJkfP1DQCMSeIApeyuVlIrFT3iv88MWWas5b3Hb8joQrxsofDUH6u2dNSrWjrvBpJpW_YAZJx6np1kxraRL6FjB4BkMFn406GOpMyXL8NB_l4Bbo9cvRDNd0Nd_BTb45fvymfp3txrFjeI183XzPTjhSfqn72SyDURj_NQbna2oL8FklM9NcI4302rVcnSho4RnAbQG4xtuBFXnQ_j-OGSrBhnqDqZb6uct63n7LMpqBfp5wx3E2BeI9DXIO6UiULKHY-KbXNMqgWDWvbuYvhczUj5mqjPssvsiEe3kX4Yo2wH5Dk9L2TaAUgw&user_locale=en-GB from this server.

I'm getting it when I try to add device to Home Smart app.

**Comment by Fleker** [comment]
How do you arrive at that error?

**Comment by Milan991** [comment]
From Smart Home Android App, when I go to Add->Set up device and select my device.

**Comment by Fleker** [comment]
Have you changed the URL for auth and token in the console?

**Comment by Milan991** [comment]
Yes. You can see it in the picture below:
![image](https://user-images.githubusercontent.com/13959599/78304756-b8adaa80-753f-11ea-8542-a4aec5c6feb1.png)

**Comment by marcnesello** [comment]
Hi Milan991,

I had the same issue. 
After following this instruction (https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation), I was able to add the device to my Google Home App.

kind regards
Marc

**Comment by proppy** [comment]
@marcnesello thanks for figuring a workaround, it seems like a consequence of a recent update to cloud functions:

From https://cloud.google.com/functions/docs/securing/managing-access-iam#allowing_unauthenticated_function_invocation
> Note: As of January 15, 2020, HTTP functions require authentication by default. You can specify whether a function allows unauthenticated invocation at or after deployment.

Looks like the restriction might be implemented sightly differently from Firebase functions.:

From: https://firebase.google.com/docs/functions/callable#write_and_deploy_the_callable_function
> Caution: New HTTP and HTTP callable functions deployed with any Firebase CLI lower than version 7.7.0 are private by default and throw HTTP 403 errors when invoked. Either explicitly make these functions public, or update your Firebase CLI before you deploy any new functions.

@Milan991 can you confirm if updating the `firebase-tools==7.7.0` fixes the issue for you?

**Comment by Milan991** [comment]
@marcnesello Thanks, that have solved my issue.
@proppy I've solved issue by @marcnesello workaround. I had error with newest version of firebase-tools.
