### ISSUE TITLE
When stream security camera on TV using Google Home speaker, does the stream go through Google home?

### ISSUE THREAD

**Issue by alshaboti** [actions-on-google/smart-home-local#25]
How does Google home manage the connection to stream security camera video to a smart TV? 
[here](https://support.google.com/googlenest/answer/7529598?hl=en)

Does Google home work as a proxy when camera is streaming the video, or somehow it commands the TV to pull stream directly from the camera without Google home in the middle?

I know that Google home SDK can bypass the cloud, but how it works locally?

Is it?

Security camera -> Google home -> smart TV
or Google home manage to make a direct connection? if yes, then How?

Security camera -> smart TV

**Comment by Fleker** [comment]
Camera streaming uses [Google Cast](https://developers.google.com/cast) to create a cloud-based stream from the camera to the TV.
