### ISSUE TITLE
Local execution on Google Home optional device

### ISSUE THREAD

**Issue by prvsousa** [actions-on-google/smart-home-local#26]
Hello,

I was wondering if I can deploy this solution without a Google Home or Google Nest but instead with a Raspberry PI that simulates a Google Home with the Google Assistant SDK?

Thank you, in advance.

**Comment by Fleker** [comment]
As noted [in the documentation](https://developers.google.com/assistant/smarthome/concepts/local):

> Google Home or Google Nest devices can load and run your app on-device.

Other devices cannot do this.

**Comment by prvsousa** [comment]
Ok thank you.
