### ISSUE TITLE
How can the local app find my device if the device does not support the mDNS,uPnP or udp？

### ISSUE THREAD

**Issue by liusseu** [actions-on-google/smart-home-local#27]
In the document， it says 'No modification of your hardware is expected to integrate local fulfillment.'
But if my device does not support mDNS and uPnP, and it also not listen on a port for the udp, i think in this conditon i have to modify my decvice, does it right?

**Comment by Fleker** [comment]
How does your device communicate?

**Comment by liusseu** [comment]
> How does your device communicate?

I user CoAP.I think if i want use the local home control ，i have to add the mDNS,uPnP or udp to my device's Firmware . Does it true?

**Comment by Fleker** [comment]
Yes, CoAP is not a supported protocol. You'd need to let your device support one of the supported communication protocols to use Local Home SDK.

**Comment by devunwired** [comment]
There are two protocols to consider for your device: discovery and control. CoAP uses UDP for control (which is supported), so while it's not supported natively you could implement it in local fulfillment for control.

> Note: SDK v1.0 currently only supports UDP write, which might be a blocker here until UDP reads are supported.

Discovery is how Google finds your devices on the network. Here CoAP is less prescriptive and could use mDNS, UDP multicast, or something else. Depending on the underlying discovery mechanism your device uses, you may be able to implement the necessary scan configuration without switching protocols in your firmware.
