### ISSUE TITLE
Missing local sync

### ISSUE THREAD

**Issue by xLerate** [actions-on-google/smart-home-local#28]
hi,

the last days i intensivly studied the new local home sdk. but i'm wondering why there is no local sync request. how GA should detect new installed local devices (may be behind a hub device)? or i'm missing something?

**Comment by devunwired** [comment]
Thanks for trying out the Local Home SDK! I would recommend starting with the [Local Fulfillment Guide](https://developers.google.com/assistant/smarthome/concepts/local) if you haven't read it already. It explains the overall concept of local fulfillment and how it fits in with smart home Actions.

Regarding `SYNC`, this is still handled by your cloud fulfillment. The local path currently only handles `EXECUTE` intents, so a cloud integration is needed as a companion to handle `SYNC` and `QUERY`.

Feel free to file any general development questions you have while working with the platform on StackOverflow under [google-smart-home](http://stackoverflow.com/questions/tagged/google-smart-home).
