### ISSUE TITLE
If the local sdk support CameraStream traits

### ISSUE THREAD

**Issue by liutuzhao** [actions-on-google/smart-home-local#29]
We tried the local sdk and handled the SYNC response with  otherDeviceIds.  
The scan config should be ok because our local app already received the  IDENTITY request with with expected udp payload.
 The IDENTITY response should be ok, because the local platform should already passed check the "verificationId",  becasuse if I set the verificationId to some string else  it says not passed verification.

The problem is when I tried "show the camera",  the local fulfilment execute callback function not triggered. 

I tried the lamp straits sample， it looks like it works well.
Does the local sdk not support CameraStream traits ????

**Comment by liutuzhao** [comment]
PS.  In this situation, my firebase cloud funtion still received the "action.devices.commands.GetCameraStream" command.

**Comment by proppy** [comment]
CameraStream is not currently supported by local fulfillment as documented on https://developers.google.com/assistant/smarthome/traits/camerastream.
