### ISSUE TITLE
UDP discovery doesn't start

### ISSUE THREAD

**Issue by GatienB** [actions-on-google/smart-home-local#3]
Hi,

I setup up this sample but it seems that the Google Home doesn't start the udp discovery so it calls every time the server (running with ngrok) to execute a command.

**Comment by Fleker** [comment]
Are you able to find your page if you open chrome://inspect/#devices on your dev machine (assuming it's on the same network)?

Did you resync your devices and reboot your device before trying it?

**Comment by GatienB** [comment]
No I can't see my page even though it's on the same network.
What do you mean by "devices" and "device" ?
I rebooted the google home and as device I have the "smart-home-local/device" running

**Comment by Fleker** [comment]
Have you sent a SYNC response to the homegraph after adding the logic in your webhook to send the `localDeviceIds` field for a given JSON device?

Once you do that, you should reboot your Google Home and then you should see your webpage appear.

**Comment by GatienB** [comment]
I retried to setup and now the udp discovery works ! I think it had badly configured google assistant.
Device is also locally controllable.
But I still can't see the webpage on chrome://inspect/#devices

**Comment by Fleker** [comment]
Okay, well I'm glad that it is working now.

**Comment by GatienB** [comment]
There is one more thing, even if I can't see the webpage on chrome://inspect/#devices I should be able to see logs when I connect to http://local-dev-server-hostname-or-ip:8080/ but the only log is : 
```
Uncaught ReferenceError: cast is not defined
    at new pc (smarthome_sdk.js:54)
    at new V (smarthome_sdk.js:197)
    at Pg (smarthome_sdk.js:200)
    at W.l.getDeviceManager (smarthome_sdk.js:200)
    at W.l.onExecute (smarthome_sdk.js:201)
    at Module../index.ts (index.ts:22)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```
It appears at this line : `if (cast.__platform__ && cast.__platform__.channel)`
in the Local Home SDK : `//www.gstatic.com/eureka/smarthome/smarthome_sdk.js`
Maybe you know what's wrong ?

**Comment by Fleker** [comment]
That will work if you're loading it on your Google Home. It will report an error on a different device though.

**Comment by devunwired** [comment]
Hi @GatienB, as Nick mentioned the Local Home SDK is only available when running the app on a supported Home/Nest device (such as a Google Home or Nest Hub). If your app is still not downloading onto the Home device, here's a few things for you to try:

1. Make sure you have entered the URL where your development app is hosted into the **Test** > **On device testing** section of the Actions console and clicked **SAVE** (more details in the [developer guide](https://developers.google.com/actions/smarthome/develop/local#3_test_and_debug_your_app))
1. If you are serving from a local dev server on your development machine, make sure your machine and Home/Nest device are on the same local network (i.e. visible to each other).
1. If you are unable to load the app from a local server, try deploying your test app to a hosting service such as [Firebase Hosting](https://firebase.google.com/docs/hosting) and entering that URL in the console instead.

You should see something similar to the following screenshot when you can see your device with the app loaded using `chrome://inspect/#devices`
![inspect](https://user-images.githubusercontent.com/215725/61894407-9f8f2d00-aecd-11e9-9ebb-a8dab49eb19e.png)

**Comment by GatienB** [comment]
Thank you for your help it works now !

**Comment by ankitb11** [comment]
i am having the same issue. google home doesnt even start UDP discovery. i think maybe something is missing in the tutorial.

**Comment by ankitb11** [comment]
> Have you sent a SYNC response to the homegraph after adding the logic in your webhook to send the `localDeviceIds` field for a given JSON device?
> 
> Once you do that, you should reboot your Google Home and then you should see your webpage appear.

How does one do that?
