### ISSUE TITLE
How to send multiple headers with DataFlow.HttpRequestData

### ISSUE THREAD

**Issue by joaoricardo000** [actions-on-google/smart-home-local#33]
Sending a single one works fine:
```
  const httpRequest = new DataFlow.HttpRequestData();
...
  httpRequest.headers = `custom-token:${data.token}`;
...
```

The issue is when I try to send two:
```
  const httpRequest = new DataFlow.HttpRequestData();
...
  httpRequest.headers = [
      `custom-token:${data.token}`,
      `custom-uuid:${data.uuid}`,
  ].join("; ");
...
```

According to the [docs](https://developers.google.com/assistant/smarthome/reference/local/classes/smarthome.dataflow.httprequestdata#headers) `headers` is a  `string`, but the description is a `List of HTTP headers for the request`.   
  
How do I send multiple headers?  
I already tested multiple `.join()` options, including `\n` that causes the `headers` to be not sent at all, but throws no error.  
  
Any ideas?

**Comment by proppy** [comment]
@joaoricardo000 Ack, the documentation should be better for this. Can you try out if `\r\n\ works for you?

**Comment by joaoricardo000** [comment]
Hi @proppy, `\r\n` works!  
Thanks for the help.

**Comment by devunwired** [comment]
[SDK v1.1.0](https://github.com/actions-on-google/local-home-sdk/releases/tag/v1.1.0) was just published, which now includes an object type for HTTP headers instead of requiring a formatted string.
