### ISSUE TITLE
TypeError: handler is not a function

### ISSUE THREAD

**Issue by grant100** [actions-on-google/smart-home-local#34]
I am getting this error in the cloud console when setting this local home fulfillment example app:

 "TypeError: handler is not a function
    at Function.<anonymous> (/srv/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:180:29)
    at Generator.next (<anonymous>)
    at /srv/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:18:12)
    at Function.handler (/srv/node_modules/actions-on-google/dist/service/smarthome/smarthome.js:174:16)
    at Object.<anonymous> (/srv/node_modules/actions-on-google/dist/assistant.js:55:32)
    at Generator.next (<anonymous>)
    at /srv/node_modules/actions-on-google/dist/assistant.js:22:71
    at new Promise (<anonymous>)"

Throws a 500 and everything stops at that point.

**Comment by devunwired** [comment]
Can you elaborate a bit more on the stage where you see this message? Is it immediately upon deployment to Firebase, or is it during the period when you are linking your account or sending a command to the device?

**Comment by grant100** [comment]
Of course,

I encounter this after I have linked the account and attempt to send a command. The following is the request that is sent:


```
{
textPayload: "Request {
  "inputs": [
    {
      "context": {
        "locale_country": "US",
        "locale_language": "en"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "customData": {
                  "channel": 1,
                  "control_protocol": "TCP",
                  "leds": 16,
                  "port": 7890
                },
                "id": "strand1"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.ColorAbsolute",
                "params": {
                  "color": {
                    "name": "incandescent",
                    "spectrumRGB": 16755031
                  }
                }
              }
            ]
          }
        ]
      }
    }
  ],
  "requestId": ".."
}"
insertId:"..."
resource: {2}
timestamp:"..."
severity: "INFO"
labels: {1}
logName: "..."
trace:"..."
receiveTimestamp: "..."
}

```

**Comment by devunwired** [comment]
Thanks. So this is occurring because the cloud fulfillment endpoint (Firebase function) doesn't have an `onExecute()` handler in the sample (we should add one as a fallback), which is causing the client library to throw an error when an `EXECUTE` intent is received.

However, if you have local fulfillment configured and running you should not encounter this because the Assistant will only attempt to call the cloud if the local path is not configured or fails to respond successfully. Have you deployed the local execution app and are you able to locally discover the virtual device? Without these pieces in place, the Assistant will always fall back to the cloud.

**Comment by grant100** [comment]
I have configured and deployed the local execution app. I can see discovery packets being sent from the home device and the virtual device responding to them:


```

UDP received discovery payload: <Buffer a5 a5 a5 a5> from: { address: 'X.X.X.X', family: 'IPv4', port: 3312, size: 4 }
UDP sent discovery response: <Buffer a5 62 69 64 67 73 74 72 61 6e 64 31 65 6d 6f 64 65 6c 69 66 61 6b 65 63 61 6e 64 79 66 68 77 5f 72 65 76 65 65 76 74 2d 31 66 66 77 5f 72 65 76 67 76 ... 17 more bytes> to: { address: 'X.X.X.X', family: 'IPv4', port: 3312, size: 4 }

```

**Comment by devunwired** [comment]
Are you able to see your local app running on the device via `chrome://inspect`? ([test the local app](https://github.com/actions-on-google/smart-home-local#test-the-local-execution-app))
You should see an `IDENTIFY` intent in the console logs when the virtual device responds to the scan. If all that is successful, then a command to turn on the light should route locally to the virtual device rather than the cloud.

**Comment by grant100** [comment]
For whatever reason, it shows up for a brief moment then disappears. I have two home devices and they each pop in and out about every second or so. I click on inspect but I don't see anything in the logs. Not sure why the devices appear then disappear.

**Comment by devunwired** [comment]
> The chrome inspection of the devices have stopped disappearing, and the logs show the app is ready. However, it doesn't look like the home devices are trying to discover the device anymore.

This is an indication that the scan configuration is either not correct or no longer enabled. You may need to verify that your Actions project still has the correct UDP scan configuration, re-save it, and re-enable test mode in the console.

> The chrome inspection logs also don't show any sort of IDENTIFY being sent.

This will show once a device has been successfully discovered using the chosen scan configuration. The `IDENTIFY` intent passes the discovered device to your app in order for you to confirm the device ID based on the scan data.

**Comment by devunwired** [comment]
Regarding the original issue, 6b3cfdee25758733676e2b50d39a9bf5409fce7d adds cloud fulfillment handlers with clearer error messages.
