### ISSUE TITLE
action.devices.commands.selectChannel empty json

### ISSUE THREAD

**Issue by enccompany** [actions-on-google/smart-home-local#41]
When using Local fulfillment | Actions on Google Smart Home, the device is unable to process the request because the command payload is empty

action.devices.commands.OnOff:

URI: /
Method: POST
Arguments: 1
 plain: {"on":false}
 or
 plain: {"on":true}

`{"inputs":[{"context":{"locale_country":"US","locale_language":"en"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"1"}],"execution":[{"command":"action.devices.commands.OnOff","params":{"on":true}}]}]}}],"requestId":"2684167294084643688"}`

action.devices.commands.selectChannel:

URI: /
Method: POST
Arguments: 1
 plain: {}

`{"inputs":[{"context":{"locale_country":"US","locale_language":"es"},"intent":"action.devices.EXECUTE","payload":{"commands":[{"devices":[{"id":"1"}],"execution":[{"command":"action.devices.commands.selectChannel","params":{"channelNumber":"200"}}]}]}}],"requestId":"13659619173073600206"}`

**Comment by proppy** [comment]
Can you paste the full EXECUTE intent payload for the failure case you're experiencing? (I do see the `action.devices.commands.selectChannel` command in your original submission).

**Comment by enccompany** [comment]
Nevermind. The getDataForCommand(command, params) at bundle.js was ignoring any command but `action.devices.commands.OnOff`
