### ISSUE TITLE
UDP Discovery doesnt work

### ISSUE THREAD

**Issue by ankitb11** [actions-on-google/smart-home-local#5]
Hi,

i dont see google home trying to do a UDP discovery, for my local device. I see that @GatienB had the same issue, which was resolved by retrying the setup, but i am wondering if there is some other issue, and people trying it for the first time are misssing something. Can you please help?

Thanks

**Comment by ankitb11** [comment]
And no, i dont see my device under chrome://inspect, also i tried to print some logs in my device code to see, if the UDP discovery is working. nothing is being printed.

**Comment by youngda** [comment]
me too,i dont see my device under chrome://inspect,,Is this what is the reason

**Comment by extesy** [comment]
@ankitb11 I see you've closed this issue. So how did you end up fixing the problem?
