### ISSUE TITLE
Updated Version on the Local SDK

### ISSUE THREAD

**Issue by pirakleous** [actions-on-google/smart-home-local#54]
Hello,

As per the release of the local home sdk [1.4.0](https://github.com/actions-on-google/local-home-sdk/blob/master/CHANGELOG.md#140---2020-11-16) queries can be supported locally now. 

However, from the Chrome debug logs i see that the SDK version which is fetched from [here](www.gstatic.com/eureka/smarthome/smarthome_sdk.js) is "1.3.1". 

Can we have the latest version of the SDK please to check if the queries are working locally or is there any other way to get the latest version?

Thanks

**Comment by proppy** [comment]
Sample has been updated to demonstrate `QUERY` intent handling:
https://github.com/actions-on-google/smart-home-local/commit/0a827cad923e31380f813eaae8cba39799b9d6e8
