### ISSUE TITLE
unable to control local device, request still going to cloud

### ISSUE THREAD

**Issue by ankitb11** [actions-on-google/smart-home-local#6]
Hi,

So i can see the UDP discovery happening, but i cant see to have local execution for my device. i tried to run app locally(didnt see any console logs being printed for IdentifyResponse) and also tried to host in on firebase and use the firbase URL for device testing, that didnt work either. what am i missing here? also cant see my device in chrome://inspect.
Any Ideas?
Thanks

**Comment by ankitb11** [comment]
further on this issue. it gets resolved when i have my local dev server running and exposed through ngrok. but when i close the dev server, i cant control the device, although ping is still working. do i have to have the app code running? is it not possible to control a local device forever, once it has been identified?

**Comment by Fleker** [comment]
While execution happens locally, SYNC and QUERY are still network based and the existence of a server is required for nominal operation.

**Comment by ankitb11** [comment]
for local devices, i don't think Query is executed, is it? The only handlers we write is for execute and identify .

Also, How often does sync happen, anyway to not do that every time for a local device?

**Comment by devunwired** [comment]
Hi @ankitb11, can you clarify if this happens immediately after you close the local dev server or if your failed attempt to execute comes after some time?

Let me explain in a bit more detail how things work during development:

1. The Home device checks in with the **On device testing** URL after a reboot and downloads your local execution JavaScript.
1. From that point on, your app remains running locally on the Home device unless you experience some error in DevTools severe enough to cause a crash. If that happened, you would need to reboot the Home device.
1. Home devices reboot nightly, at which point they will attempt to download the local app from that URL again. If the server is not available, that would fail.

If this happens after a device reboot of some kind, it's working as intended. Either way, this wouldn't be a bug with the sample code so I'm going to keep this issue closed. If you can reproduce a case where you lose local execution immediately after shutting down your local server, please file an issue in the [official issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327).
