### ISSUE TITLE
decoding not working for python device

### ISSUE THREAD

**Issue by ankitb11** [actions-on-google/smart-home-local#7]
Hi,

So i am writing my local device in python, with the same fields as in discoverData in javascript device. i encoded it using cbor and sent it, the client cant parse it. i thought maybe the object is python dictionary, so i even converted it to json and encoded and sent it, again. Nothing worked.

Am i missing something here?

Thanks

**Comment by ankitb11** [comment]
this is how discoveryData is looking like after decoding 

Map(6) {Uint8Array(4) => 2, Uint8Array(6) => Uint8Array(1), Uint8Array(4) => 7890, Uint8Array(6) => Uint8Array(1), Uint8Array(5) => Uint8Array(1), …}

**Comment by devunwired** [comment]
Hi @ankitb11, in the future I would recommend posting general development questions like this on StackOverflow. You can use the [google-smart-home](https://stackoverflow.com/questions/tagged/google-smart-home) tag for questions related to the smart home API and local home SDK.
