### ISSUE TITLE
UDP discovery packet must be base64 or hex string

### ISSUE THREAD

**Issue by veonua** [actions-on-google/smart-home-local#8]
it is not possible to pass 
0x00 and 0xFF symbols

**Comment by devunwired** [comment]
Hi @veonua, it looks like you might be reporting an issue with the Local Home SDK or the Actions Console rather than the sample code. If so, can you file an issue on the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327) for the platform?

**Comment by veonua** [comment]
As it is only example of Local Home SDK in whole Internet and official documentation is autogenerated and has no linking between elements. I think it would be beneficial for community to extend this sample to support binary protocol. 

But I can copy the issue to internal bug tracker

Andrew

**Comment by devunwired** [comment]
Thank you!
We will update the sample code to reflect any changes in platform support.
