### ISSUE TITLE
UdpResponseData is missing, it is impossible to get back UDP result

### ISSUE THREAD

**Issue by veonua** [actions-on-google/smart-home-local#9]
so GoogleHome would only send datagrams, and UDP handshake is not possible

**Comment by devunwired** [comment]
Hi @veonua, it looks like you might be reporting an issue with the Local Home SDK or the Actions Console rather than the sample code. If so, can you file an issue on the [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284327) for the platform?

**Comment by devunwired** [comment]
Closing as this issue was filed on the [public tracker](https://issuetracker.google.com/issues/139276385)
